<?php

namespace ContainerXNkxqgI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YjaJcAPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YjaJcAP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YjaJcAP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avisRepository' => ['privates', 'App\\Repository\\AvisRepository', 'getAvisRepositoryService', true],
            'camping' => ['privates', '.errored..service_locator.YjaJcAP.App\\Entity\\Camping', NULL, 'Cannot autowire service ".service_locator.YjaJcAP": it needs an instance of "App\\Entity\\Camping" but this type has been excluded in "config/services.yaml".'],
        ], [
            'avisRepository' => 'App\\Repository\\AvisRepository',
            'camping' => 'App\\Entity\\Camping',
        ]);
    }
}
