<?php

namespace ContainerXNkxqgI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WBnEqUYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WBnEqUY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WBnEqUY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\Admin\\AvisController::avisByCamping' => ['privates', '.service_locator.YjaJcAP', 'get_ServiceLocator_YjaJcAPService', true],
            'App\\Controller\\Admin\\AvisController::delete' => ['privates', '.service_locator.SWeuZME', 'get_ServiceLocator_SWeuZMEService', true],
            'App\\Controller\\Admin\\AvisController::edit' => ['privates', '.service_locator.SWeuZME', 'get_ServiceLocator_SWeuZMEService', true],
            'App\\Controller\\Admin\\AvisController::index' => ['privates', '.service_locator.T61jM.4', 'get_ServiceLocator_T61jM_4Service', true],
            'App\\Controller\\Admin\\AvisController::new' => ['privates', '.service_locator.CrRgyup', 'get_ServiceLocator_CrRgyupService', true],
            'App\\Controller\\Admin\\AvisController::show' => ['privates', '.service_locator.Qa1ff8U', 'get_ServiceLocator_Qa1ff8UService', true],
            'App\\Controller\\Admin\\CampingController::delete' => ['privates', '.service_locator.CrRgyup', 'get_ServiceLocator_CrRgyupService', true],
            'App\\Controller\\Admin\\CampingController::edit' => ['privates', '.service_locator.JB_YgeR', 'get_ServiceLocator_JBYgeRService', true],
            'App\\Controller\\Admin\\CampingController::index' => ['privates', '.service_locator.ttt_q7L', 'get_ServiceLocator_TttQ7LService', true],
            'App\\Controller\\Admin\\CampingController::new' => ['privates', '.service_locator.LNwsF6h', 'get_ServiceLocator_LNwsF6hService', true],
            'App\\Controller\\Admin\\CampingController::show' => ['privates', '.service_locator.YjaJcAP', 'get_ServiceLocator_YjaJcAPService', true],
            'App\\Controller\\Front\\AvisController::delete' => ['privates', '.service_locator.SWeuZME', 'get_ServiceLocator_SWeuZMEService', true],
            'App\\Controller\\Front\\AvisController::edit' => ['privates', '.service_locator.SWeuZME', 'get_ServiceLocator_SWeuZMEService', true],
            'App\\Controller\\Front\\AvisController::new' => ['privates', '.service_locator.CrRgyup', 'get_ServiceLocator_CrRgyupService', true],
            'App\\Controller\\Front\\CampingController::delete' => ['privates', '.service_locator.CrRgyup', 'get_ServiceLocator_CrRgyupService', true],
            'App\\Controller\\Front\\CampingController::edit' => ['privates', '.service_locator.JB_YgeR', 'get_ServiceLocator_JBYgeRService', true],
            'App\\Controller\\Front\\CampingController::index' => ['privates', '.service_locator.ttt_q7L', 'get_ServiceLocator_TttQ7LService', true],
            'App\\Controller\\Front\\CampingController::new' => ['privates', '.service_locator.LNwsF6h', 'get_ServiceLocator_LNwsF6hService', true],
            'App\\Controller\\Front\\CampingController::show' => ['privates', '.service_locator.6n9amBL', 'get_ServiceLocator_6n9amBLService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator..89.12.', 'get_ServiceLocator__89_12_Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.9QfjjfA', 'get_ServiceLocator_9QfjjfAService', true],
            'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\TestImageController::index' => ['privates', '.service_locator.xJpW8Z9', 'get_ServiceLocator_XJpW8Z9Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Admin\\AvisController:avisByCamping' => ['privates', '.service_locator.YjaJcAP', 'get_ServiceLocator_YjaJcAPService', true],
            'App\\Controller\\Admin\\AvisController:delete' => ['privates', '.service_locator.SWeuZME', 'get_ServiceLocator_SWeuZMEService', true],
            'App\\Controller\\Admin\\AvisController:edit' => ['privates', '.service_locator.SWeuZME', 'get_ServiceLocator_SWeuZMEService', true],
            'App\\Controller\\Admin\\AvisController:index' => ['privates', '.service_locator.T61jM.4', 'get_ServiceLocator_T61jM_4Service', true],
            'App\\Controller\\Admin\\AvisController:new' => ['privates', '.service_locator.CrRgyup', 'get_ServiceLocator_CrRgyupService', true],
            'App\\Controller\\Admin\\AvisController:show' => ['privates', '.service_locator.Qa1ff8U', 'get_ServiceLocator_Qa1ff8UService', true],
            'App\\Controller\\Admin\\CampingController:delete' => ['privates', '.service_locator.CrRgyup', 'get_ServiceLocator_CrRgyupService', true],
            'App\\Controller\\Admin\\CampingController:edit' => ['privates', '.service_locator.JB_YgeR', 'get_ServiceLocator_JBYgeRService', true],
            'App\\Controller\\Admin\\CampingController:index' => ['privates', '.service_locator.ttt_q7L', 'get_ServiceLocator_TttQ7LService', true],
            'App\\Controller\\Admin\\CampingController:new' => ['privates', '.service_locator.LNwsF6h', 'get_ServiceLocator_LNwsF6hService', true],
            'App\\Controller\\Admin\\CampingController:show' => ['privates', '.service_locator.YjaJcAP', 'get_ServiceLocator_YjaJcAPService', true],
            'App\\Controller\\Front\\AvisController:delete' => ['privates', '.service_locator.SWeuZME', 'get_ServiceLocator_SWeuZMEService', true],
            'App\\Controller\\Front\\AvisController:edit' => ['privates', '.service_locator.SWeuZME', 'get_ServiceLocator_SWeuZMEService', true],
            'App\\Controller\\Front\\AvisController:new' => ['privates', '.service_locator.CrRgyup', 'get_ServiceLocator_CrRgyupService', true],
            'App\\Controller\\Front\\CampingController:delete' => ['privates', '.service_locator.CrRgyup', 'get_ServiceLocator_CrRgyupService', true],
            'App\\Controller\\Front\\CampingController:edit' => ['privates', '.service_locator.JB_YgeR', 'get_ServiceLocator_JBYgeRService', true],
            'App\\Controller\\Front\\CampingController:index' => ['privates', '.service_locator.ttt_q7L', 'get_ServiceLocator_TttQ7LService', true],
            'App\\Controller\\Front\\CampingController:new' => ['privates', '.service_locator.LNwsF6h', 'get_ServiceLocator_LNwsF6hService', true],
            'App\\Controller\\Front\\CampingController:show' => ['privates', '.service_locator.6n9amBL', 'get_ServiceLocator_6n9amBLService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator..89.12.', 'get_ServiceLocator__89_12_Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.9QfjjfA', 'get_ServiceLocator_9QfjjfAService', true],
            'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\TestImageController:index' => ['privates', '.service_locator.xJpW8Z9', 'get_ServiceLocator_XJpW8Z9Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Admin\\AvisController::avisByCamping' => '?',
            'App\\Controller\\Admin\\AvisController::delete' => '?',
            'App\\Controller\\Admin\\AvisController::edit' => '?',
            'App\\Controller\\Admin\\AvisController::index' => '?',
            'App\\Controller\\Admin\\AvisController::new' => '?',
            'App\\Controller\\Admin\\AvisController::show' => '?',
            'App\\Controller\\Admin\\CampingController::delete' => '?',
            'App\\Controller\\Admin\\CampingController::edit' => '?',
            'App\\Controller\\Admin\\CampingController::index' => '?',
            'App\\Controller\\Admin\\CampingController::new' => '?',
            'App\\Controller\\Admin\\CampingController::show' => '?',
            'App\\Controller\\Front\\AvisController::delete' => '?',
            'App\\Controller\\Front\\AvisController::edit' => '?',
            'App\\Controller\\Front\\AvisController::new' => '?',
            'App\\Controller\\Front\\CampingController::delete' => '?',
            'App\\Controller\\Front\\CampingController::edit' => '?',
            'App\\Controller\\Front\\CampingController::index' => '?',
            'App\\Controller\\Front\\CampingController::new' => '?',
            'App\\Controller\\Front\\CampingController::show' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::register' => '?',
            'App\\Controller\\TestImageController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Admin\\AvisController:avisByCamping' => '?',
            'App\\Controller\\Admin\\AvisController:delete' => '?',
            'App\\Controller\\Admin\\AvisController:edit' => '?',
            'App\\Controller\\Admin\\AvisController:index' => '?',
            'App\\Controller\\Admin\\AvisController:new' => '?',
            'App\\Controller\\Admin\\AvisController:show' => '?',
            'App\\Controller\\Admin\\CampingController:delete' => '?',
            'App\\Controller\\Admin\\CampingController:edit' => '?',
            'App\\Controller\\Admin\\CampingController:index' => '?',
            'App\\Controller\\Admin\\CampingController:new' => '?',
            'App\\Controller\\Admin\\CampingController:show' => '?',
            'App\\Controller\\Front\\AvisController:delete' => '?',
            'App\\Controller\\Front\\AvisController:edit' => '?',
            'App\\Controller\\Front\\AvisController:new' => '?',
            'App\\Controller\\Front\\CampingController:delete' => '?',
            'App\\Controller\\Front\\CampingController:edit' => '?',
            'App\\Controller\\Front\\CampingController:index' => '?',
            'App\\Controller\\Front\\CampingController:new' => '?',
            'App\\Controller\\Front\\CampingController:show' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:register' => '?',
            'App\\Controller\\TestImageController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
