<?php

namespace ContainerXNkxqgI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CrRgyupService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CrRgyup' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CrRgyup'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'camping' => ['privates', '.errored..service_locator.CrRgyup.App\\Entity\\Camping', NULL, 'Cannot autowire service ".service_locator.CrRgyup": it needs an instance of "App\\Entity\\Camping" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'camping' => 'App\\Entity\\Camping',
            'entityManager' => '?',
        ]);
    }
}
