<?php

namespace ContainerJt3HKLx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvisController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Front\AvisController' shared autowired service.
     *
     * @return \App\Controller\Front\AvisController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Front/AvisController.php';

        $container->services['App\\Controller\\Front\\AvisController'] = $instance = new \App\Controller\Front\AvisController(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Front\\AvisController', $container));

        return $instance;
    }
}
