<?php

namespace ContainerJt3HKLx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampingTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CampingType' shared autowired service.
     *
     * @return \App\Form\CampingType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CampingType.php';

        return $container->privates['App\\Form\\CampingType'] = new \App\Form\CampingType();
    }
}
