<?php

namespace ContainerJt3HKLx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCamping4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.YjaJcAP.App\Entity\Camping' shared service.
     *
     * @return \App\Entity\Camping
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.YjaJcAP": it needs an instance of "App\\Entity\\Camping" but this type has been excluded in "config/services.yaml".');
    }
}
