# config/services.yaml

# Paramètres globaux
parameters:
    OPENAI_API_KEY: '%env(OPENAI_API_KEY)%'
    deepl.api_key: '%env(DEEPL_API_KEY)%'

services:
    # Configuration par défaut pour tous vos services
    _defaults:
        autowire: true      # Injection automatique des dépendances
        autoconfigure: true # Enregistrement automatique (Command, EventSubscriber, …)

    # Charge automatiquement toutes les classes de src/ comme services,
    # à l’exception de celles listées dans exclude
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Liaison explicite du paramètre pour TranslateService
    App\Service\TranslateService:
        arguments:
            $apiKey: '%deepl.api_key%'
